services:
  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static-files:/usr/share/nginx/html  # Named volume
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      target: production
    volumes:
      - static-files:/usr/share/nginx/html  # Same named volume

  backend:
    build:
      context: ./backend
      target: production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
  
  db: 
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - portfolio_db_data:/var/lib/postgresql/data
      
volumes:
  static-files:  # Define the volume
  portfolio_db_data: