services:
  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"  # Using port 5000 as you requested
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      target: production
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      target: production
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production